### ISSUE TITLE
AVX512 Build on GCC 6.3.0

### ISSUE THREAD

**Issue by fritterhoff** [vectorclass/version1#1]
Hi,

I recently tried to build an executable using GCC 6.3.0 in combination with the flag `-march=skylake-avx512`. Sadly I got some errors telling me that the Methods `_mm512_cvtss_f32`, `_mm512_cvtsd_f64`, `_mm256_cvtss_f32` and `_mm256_cvtsd_f64` are unknown. 

Is there maybe a possibility of fixing this issue?

**Comment by AgnerF** [comment]
Have you tried -mavx512f ?
Please try a later version of gcc

**Comment by fritterhoff** [comment]
The repos of Debian 9 do not provide a later version of gcc ☹️

**Comment by AgnerF** [comment]
Have you tried the Clang compiler? Can you update to Debian 10?

**Comment by fritterhoff** [comment]
Debian 10 works fine but the target system runs under Debian 9 so I get errors concerning the libc version on the target system after building the executable using gcc 8 on Debian 10. 

I'll try another Compiler but currently the complete project is using GCC.

**Comment by AgnerF** [comment]
The functions _mm256_cvtss_f32, etc. are only used when compiling for AVX512. Why would a system with an old operating system and an old compiler use a new instruction set that has not hit the mainstream yet? 

You can probably work around the problem with something like:
```
static inline float _mm256_cvtss_f32 (__m256 a) {
   return _mm_cvtss_f32(_mm256_castps256_ps128(a));
}
```

But you are surely asking for trouble, because the vector class library has not been tested with Gcc version 6, and you cannot be sure that AVX512 bugs have been weeded out in gcc 6.

**Comment by fritterhoff** [comment]
> Why would a system with an old operating system and an old compiler use a new instruction set that has not hit the mainstream yet?

Well Debian 9 isn't so old and an update of my existing software will probably require more changes...
